describe('Homepage spec', () => {
  it('Visits Home Page', () => {
    cy.visit('http://localhost:5173/')
    cy.get('[data-cy="h1Welcome"]').should('have.text','Welcome to D-Block CO2 Monitor')
  })
  it('Visits Room D201', () => {
    cy.visit('http://localhost:5173/')
    cy.get('[data-cy="D201"]').click()
    cy.url().should('eq', 'http://localhost:5173/D-Block/D201')
    cy.wait(100)
    // cy.get('[id="reactgooglegraph-25"]').should('be.visible')
  })
  it('Visits Room D202', () => {
    cy.visit('http://localhost:5173/')
    cy.get('[data-cy="D202"]').click()
    cy.url().should('eq', 'http://localhost:5173/D-Block/D202')
    cy.wait(100)
    // cy.get('[id="reactgooglegraph-20"]').should('be.visible')
  })
  it('Visits Room D207', () => {
    cy.visit('http://localhost:5173/')
    cy.get('[data-cy="D207"]').click()
    cy.url().should('eq', 'http://localhost:5173/D-Block/D207')
    cy.wait(100)
    // cy.get('[id="reactgooglegraph-5"]').should('be.visible')
  })
  it('Visits Room D207 TD', () => {
    cy.visit('http://localhost:5173/')
    cy.get('[data-cy="D207 TD"]').click()
    cy.url().should('eq', 'http://localhost:5173/D-Block/D207%20TD')
    cy.wait(100)
    // cy.get('[id="reactgooglegraph-5"]').should('be.visible')
  })
  it('Visits Sensor History', () => {
    cy.visit('http://localhost:5173/')
    cy.get('[data-cy="SensorHistory"]').click()
    cy.url().should('eq', 'http://localhost:5173/SensorHistory')
    cy.get('[class="recharts-wrapper"]').should('be.visible')
  })
})